language: go
sudo: required

addons:
  apt:
    update: true

install:
  - go get -v github.com/gohugoio/hugo

script:
  - hugo

after_script:
  - chmod +x ./deploy.sh
  - ./deploy.sh

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/xuchengpeng/hugo-blog.git # GitHub博客仓库的地址
