language: go
sudo: required

go: 1.x

addons:
  apt:
    update: true

install:
  - chmod ./install_hugo.sh
  - ./install_hugo.sh

script:
  - hugo

after_script:
  - chmod +x ./deploy.sh
  - ./deploy.sh

branches:
  only:
    - hugo

env:
 global:
   - GH_REF: github.com/xuchengpeng/xuchengpeng.github.io.git # GitHub博客仓库的地址
