baseurl = "http://xuchengpeng.com/"
languageCode = "en"
title = "xuchengpeng"
theme = "whiteplain"
paginate = "10"

copyright = "&copy; Copyright 2018 xuchengpeng"
pygmentsCodefences = true

[permalinks]
  post = "/:year/:month/:day/:filename/"

[params.author]
  name = "xuchengpeng"
  
  github = "xuchengpeng"
  bitbucket = "xuchengpeng"
  email = "xucp@outlook.com"

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[Params.valine]
    enable = true
    appId = '8cGx0mI721mXnuSact0PLKmV-gzGzoHsz'
    appKey = 'eQc0CtLv9s4VTdObz6ux8lVW'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'wavatar' 
    placeholder = 'Leave your comments here...'
    visitor = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
  name = "归档"
  weight = 1
  identifier = "archives"
  url = "/archives/"
[[menu.main]]
  name = "分类"
  weight = 2
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "标签"
  weight = 3
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "留言"
  weight = 4
  identifier = "guestbook"
  url = "/guestbook/"
[[menu.main]]
  name = "关于"
  weight = 5
  identifier = "about"
  url = "/about/"
