name = "Whiteplain"
license = "GPLv3"
description = "Simple and functional theme for Hugo"
homepage = "http://xuchengpeng.com"
tags = ["blog", "white", "simple"]
features = ["blog", "white", "simple"]
min_version = "0.30"

[author]
  name = "xuchengpeng"
  homepage = "http://xuchengpeng.com"
