name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unix-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Check out hugo-blog
        uses: actions/checkout@v3
      - name: Clone submodule
        run: git submodule update --init --recursive
      - name: Build site
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
