name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unix-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out hugo-blog
        uses: actions/checkout@v2
      - name: Config git
        run: git config user.name "xuchengpeng" && git config user.email "330476629@qq.com"
      - name: Clone submodule
        run: git submodule update --init --recursive
      - name: Update submodule
        run: git submodule update --remote --merge
