name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unix-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out hugo-blog
        uses: actions/checkout@v2
      - name: Delete All Themes
        run: rm -rf themes/PaperMod themes/minos themes/whiteplain
      - name: Add PaperMod
        run: git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
      - name: Add PaperMod
        run: git config user.name "xuchengpeng" && git config user.email "330476629@qq.com" && git add . && git commit -m "add PaperMod submodule"
      - name: Upload
        run: git push
